# @package dataset.cingulate_ACCpatterns_1
dataset_name: cingulate_ACCpatterns_1
numpy_all: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rlabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rlabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rlabels
input_size: (1, 17, 40, 38)
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/csv/ACCpatterns/ACCpatterns_1_without_headers.csv
subject_labels_file: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/csv/ACCpatterns/all.csv
subject_column_name: 'long_name'
label_names: ["Right_PCS"]
n_max: 1099
