# @package _global_
numpy_all: /volatile/jc225751/Runs/43_supervised_contrastive_ACCpatterns/Input/Rskeleton_ACCpatterns_test.npy
subjects_all: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rskeleton_subject.csv
foldlabel_all: /volatile/jc225751/Runs/43_supervised_contrastive_ACCpatterns/Input/Rlabel_ACCpatterns_test.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rlabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/crops/2mm/CINGULATE/mask/Rlabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/ACCpatterns/train_val_ACCpatterns.csv
subject_labels_file: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/csv/ACCpatterns/all.csv
subject_column_name: 'long_name'
label_names: ["Right_PCS"]