# @package _global_
batch_size: 16
pin_mem: True
input_size: (1, 20, 40, 40)
patch_size: [1, 12, 24, 24]
max_angle: 10
checkerboard_size: 4
partition: [0.8, 0.2]
num_cpu_workers: 48
keep_bottom: True
mode: encoder
depth_decoder: 3
temperature: 0.1
sigma: 5
lr: 2e-4
weight_decay: 5e-5
max_epochs: 300
drop_rate: 0.0
nb_epochs_per_saving: 1
nb_epochs_per_tSNE: 50
nb_steps_per_flush_logs: 1
log_every_n_steps: 2
seed: 42
start_epoch: 0
checkpoint_path: 
analysis_path: 