# @package _global_
model: SimCLR_fusion
sigma_labels: 2.0
sigma: 5
drop_rate: 0.05
pretrained_model_path: #path/to/cpkt
load_encoder_only: True
freeze_encoders: False
fusioned_latent_space_size: 10
converter_activation: relu