# @package _global_
# define path and parameters needed for the classifier on the latent space
classifier_name: svm
training_embeddings: /neurospin/dico/data/deep_folding/papers/ipmi2023/models/fusion/#1/cingulate_ACCpatterns_0_embeddings/full_embeddings.csv
test_embeddings: 
embeddings_of_interest:
results_save_path:
training_labels: /neurospin/dico/data/bv_databases/human/partially_labeled/ACCpatterns/all.csv
labels_of_interest:
class_max_epochs: 5000
n_repeat: 250
classifier_seed: 24
classifier_test_size: 0.2