# @package _global_
# define path and parameters needed for the classifier on the latent space
classifier_name: svm
training_embeddings: /neurospin/dico/jlaval/Runs/01_deep_supervised/Program/Output/PCA/Preterm_Preterm_test/pca_embeddings_10.csv
test_embeddings: 
embeddings_of_interest:
results_save_path:
training_labels: /neurospin/dico/data/deep_folding/current/datasets/utrecht_dHCP/crops/2mm/CINGULATE_40wks/mask/preterm_labels_test.csv
labels_of_interest:
class_max_epochs: 5000
n_repeat: 250
classifier_seed: 24
classifier_test_size: 0.2
