# @package _global_
batch_size: 16
pin_mem: True
lr: 1e-2
weight_decay: 5.0e-05
max_epochs: 51
nb_epochs_per_saving: 1
nb_epochs_per_tSNE: -1
nb_epochs_per_matrix_plot: -1
nb_steps_per_flush_logs: 1
log_every_n_steps: 2
early_stopping_patience: 25
diff_auc_threshold: 0.4  # early stopping too
start_epoch: 0
checkpoint_path:
analysis_path: 
verbose: 1
checking: True
# Data split and subject choice
seed: 1
partition: [0.9, 0.1]
nb_subjects: -1
random: False
random_state: 25
class_weights: [19., 355.]
