defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate_HCP_half_2
  - model: SimCLR
  - mode: encoder
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings