# @package _global_
# Characterization of the DenseNet model used
backbone_name: densenet
growth_rate: 32
block_config: [6, 16]
num_init_features: 64
num_representation_features: 10
num_outputs: 10
projection_head_hidden_layers:
projection_head_type: linear